version: "3.9"  # optional since v1.27.0
networks:
  lubycash-network:
    external: true
  lubycash-api-network:
    driver: bridge
services:
  app:
    container_name: 'adonis-lubycash-api'
    build:
      context: .
      dockerfile: Dockerfile
    command: node ace serve --watch
    image: adonis-lubycash
    volumes:
      - .:/usr/app
      - /usr/app/node_modules # anonymous volume for node_modules only
    networks:
        - lubycash-api-network
        - lubycash-network
    ports:
      - '3333:3333'
    depends_on:
      - db-api

  db-api:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: api_lubycash
    ports:
      - '5435:5432'
    networks:
      - lubycash-api-network
    volumes:
       - /usr/db/var/lib/postgres2
